name: Update Website on VM

on:
  push:
    branches:
      - main  # Ou o nome do seu branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: SSH into VM and pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 443  # Porta SSH
          script: |
            cd /home/gerador_senhas
            git pull origin main
