name: Update Website on VM

on:
  push:
    branches:
      - main  # Ou o nome do seu branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VM and pull code
        uses: appleboy/ssh-action@master
        with:
          host: exemplo.com  # Substitua "exemplo.com" pelo seu nome de domínio
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 443  # Porta SSH
          script: |
            cd /home/gerador_senhas
            git pull origin main
