name: Update Website on VM

on:
  push:
    branches:
      - main  # Ou o nome do seu branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: SSH into VM and pull code
        uses: appleboy/ssh-action@master
        with:
          host:  ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Aqui está a chave privada SSH
         #password: ${{ secrets.SSH_PASSWORD_PRIVATE_KEY }}
          port: 443
          script: |
            cd /home/gerador_senhas
            git pull origin main
